# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

 
- script: |
    ls
    terraform version
  displayName: 'Prep'

- script: |
    terraform -chdir=tf init
  displayName: 'Terraform Init'

- script: |
    terraform -chdir=tf plan -var 'aws_access_key=$(Username)' -var 'aws_secret_key=$(SecretKey)' -out=tf.plan
  displayName: 'Terraform Plan'
